# Generated by Django 5.0.7 on 2024-08-07 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gride_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usina',
            new_name='Usuario',
        ),
        migrations.RenameModel(
            old_name='Relatorio',
            new_name='RelatorioConsumo',
        ),
        migrations.RenameField(
            model_name='dadosdesempenho',
            old_name='usina',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='dadosfalhas',
            old_name='usina',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='dadosintegridade',
            old_name='usina',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='relatorioconsumo',
            old_name='usina',
            new_name='usuario',
        ),
        migrations.CreateModel(
            name='RelatorioFalhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=11)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dados_relatorio', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gride_dashboard.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatorioIntegridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=11)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dados_relatorio', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gride_dashboard.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatorioProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=11)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dados_relatorio', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gride_dashboard.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatorioProjecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=11)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dados_relatorio', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gride_dashboard.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
