# Generated by Django 5.0.7 on 2024-08-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gride_dashboard', '0003_rename_relatorioprojecao_cacherelatorioconsumo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CacheRelatorioProducao',
            new_name='cache_relatorio_consumo',
        ),
        migrations.RenameModel(
            old_name='CacheRelatorioIntegridade',
            new_name='cache_relatorio_falhas',
        ),
        migrations.RenameModel(
            old_name='CacheRelatorioFalhas',
            new_name='cache_relatorio_integridade',
        ),
        migrations.RenameModel(
            old_name='CacheRelatorioConsumo',
            new_name='cache_relatorio_producao',
        ),
        migrations.RenameModel(
            old_name='CacheRelatorioProjecao',
            new_name='cache_relatorio_projecao',
        ),
        migrations.RenameModel(
            old_name='DadosDesempenho',
            new_name='dados_desempenho',
        ),
        migrations.RenameModel(
            old_name='DadosFalhas',
            new_name='dados_falhas',
        ),
        migrations.RenameModel(
            old_name='DadosIntegridade',
            new_name='dados_integridade',
        ),
    ]
