# Generated by Django 5.0.7 on 2024-08-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gride_dashboard', '0004_rename_cacherelatorioproducao_cache_relatorio_consumo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cache_relatorio_falhas',
            new_name='CacheRelatorioConsumo',
        ),
        migrations.RenameModel(
            old_name='cache_relatorio_integridade',
            new_name='CacheRelatorioFalhas',
        ),
        migrations.RenameModel(
            old_name='cache_relatorio_consumo',
            new_name='CacheRelatorioIntegridade',
        ),
        migrations.RenameModel(
            old_name='cache_relatorio_producao',
            new_name='CacheRelatorioProducao',
        ),
        migrations.RenameModel(
            old_name='cache_relatorio_projecao',
            new_name='CacheRelatorioProjecao',
        ),
        migrations.RenameModel(
            old_name='dados_desempenho',
            new_name='DadosDesempenho',
        ),
        migrations.RenameModel(
            old_name='dados_falhas',
            new_name='DadosFalhas',
        ),
        migrations.RenameModel(
            old_name='dados_integridade',
            new_name='DadosIntegridade',
        ),
    ]
