# Generated by Django 5.1 on 2024-08-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gride_dashboard', '0005_rename_cache_relatorio_falhas_cacherelatorioconsumo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CacheRelatorioFalhas',
            new_name='CacheRelatorio',
        ),
        migrations.RemoveField(
            model_name='cacherelatoriointegridade',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cacherelatorioproducao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cacherelatorioprojecao',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CacheRelatorioConsumo',
        ),
        migrations.DeleteModel(
            name='CacheRelatorioIntegridade',
        ),
        migrations.DeleteModel(
            name='CacheRelatorioProducao',
        ),
        migrations.DeleteModel(
            name='CacheRelatorioProjecao',
        ),
    ]
