# Generated by Django 5.1 on 2024-08-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gride_dashboard', '0006_rename_cacherelatoriofalhas_cacherelatorio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DadosFalhas',
            new_name='DadosFalha',
        ),
    ]
